name: Generate Snake

permissions:
  contents: write

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */12 * * *" # runs every 12 hours
  workflow_dispatch: # allows you to run manually

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Generate snake
      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: charlesms1246
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      # Step 3: Push to output branch
      - name: Push generated files
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Debug step to confirm files exist
      - name: List generated files
        run: ls -R dist
